### ISSUE TITLE
WebSocket error with meteor on NGINX webserver

### ISSUE THREAD

**Issue by stlouisweb** [meteorhacks/meteor-down#2]
I get the following error when trying to connect to a meteor instance that is on an nginx server
/usr/local/opt/nvm/v0.10.36/lib/node_modules/meteor-down/lib/mdown.js:47  
    if(error) throw error;  
                    ^  
Error during WebSocket handshake: Unexpected response code: 301

**Comment by arunoda** [comment]
MeteorDown uses a WebSocket endpoint. Have you configured nginx for WS.

**Comment by stlouisweb** [comment]
No I have not, any guidance?
Thank you

**Comment by arunoda** [comment]
Hmm. no idea.
I'm not a nginx expert.
Try googling :)

**Comment by stlouisweb** [comment]
Will do, thanks
