### ISSUE TITLE
Meteor Down output

### ISSUE THREAD

**Issue by LukeStanbery89** [meteorhacks/meteor-down#8]
Hello,

I am trying to decipher the meaning of the output. What does "XXXX/min" mean? Are those the method calls per minute? Is "XXms" the time it takes to execute each method? Are method calls made synchronously or asynchronously. I am just trying to get a grasp on what exactly is happening and how it is represented in the output. Any help is appreciated.

![screen shot 2015-04-14 at 2 51 45 pm](https://cloud.githubusercontent.com/assets/9427182/7146125/f2934320-e2b6-11e4-973d-ba0bcfa108f1.png)

Thanks,
Luke.

**Comment by arunoda** [comment]
Yes. That means XXX messages sent per minute with the 15ms response time.
They are send asynchronously.

**Comment by LukeStanbery89** [comment]
Thanks for the information.
